name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Podcast Generator - @siddydutta
        uses: siddydutta/podcast-generator@v1.0
        with:
          email: siddharthadutta@protonmail.com
          name: siddydutta
